server:
  port: 8500
  servlet:
    context-path: /ps


# DB connection and hibernate properties
spring:
  datasource:
    url: jdbc:mysql://rap-database..ap-south-1.rds.amazonaws.com:3306/rap_db
    username:
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB
      max-request-size: 10MB
      file-size-threshold: 0

app:
  aws:
    region: ap-south-1
  s3:
    bucket-name: rentaplace-media
    base-prefix: properties
    maxFileSizeMb: 8

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: TRACE
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG
    org.springframework.security.authentication.ProviderManager: DEBUG
